# Generated by Django 4.2.30 on 2026-04-23 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('View_History', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
