# Generated by Django 4.2.30 on 2026-04-24 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_product_alter_order_status_delete_orderitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
