# Generated by Django 4.2.30 on 2026-04-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_profile_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mfa_method',
            field=models.CharField(blank=True, choices=[('totp', 'TOTP'), ('sms', 'SMS')], max_length=10, null=True),
        ),
    ]
