# Generated by Django 4.2.30 on 2026-05-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_profile_mfa_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mfa_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
