# Generated by Django 4.2.30 on 2026-05-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_profile_mfa_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sms_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sms_code_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
