# Generated by Django 4.2.30 on 2026-05-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_profile_sms_code_profile_sms_code_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin'), ('it', 'IT Support')], default='student', max_length=20),
        ),
    ]
