# Generated by Django 4.2.30 on 2026-05-05 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0011_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='sms_code',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sms_code_created_at',
        ),
    ]
