# Generated by Django 4.2.30 on 2026-05-07 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin'), ('it', 'IT Support')], default='student', max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('mfa_method', models.CharField(blank=True, choices=[('totp', 'TOTP'), ('sms', 'SMS')], max_length=10, null=True)),
                ('mfa_code', models.CharField(blank=True, max_length=6, null=True)),
                ('mfa_expiry', models.DateTimeField(blank=True, null=True)),
                ('mfa_enabled', models.BooleanField(default=True)),
                ('mfa_secret', models.CharField(blank=True, max_length=32, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
