# Generated by Django 4.2.30 on 2026-05-14 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mfa_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
